/-
Copyright (c) 2024 Yizhou Tong. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yizhou Tong
-/
import SPG.Core.Algebra.AlgebraBasics
import SPG.Core.Algebra.Group
import SPG.Core.Geometry.SpatialOps
import SPG.Core.Geometry.SpinOps
import SPG.Interface.Notation
import SPG.Model.Multiferroic
import SPG.Material.MagneticGroup

namespace Demo.Multiferroic

open SPG
open SPG.Core.Algebra
open SPG.Core.Geometry.SpatialOps
open SPG.Core.Geometry.SpinOps
open SPG.Interface
open SPG.Model.Multiferroic
open SPG.Material.MagneticGroup

/--
Cr2O3 (Chromium Oxide) - The classic magnetoelectric material.
Space Group: R-3c (#167)
Magnetic Group: -3'm' (D3d magnetic) or simpler 3'm'?
Actually, Cr2O3 has corundum structure.
The magnetic point group is -3'm' (using international notation).
Generators:
1. -3' (Inversion * 3-fold rotation * Time Reversal?)
   No, -3 is 3bar (rotoinversion).
   Usually Cr2O3 symmetry is described as D3d (3m) with broken T.
   The magnetic point group is 3'm' or -3'm.
   Let's use the known result: The group is generated by:
   - C3z (Spatial)
   - I * T (Inversion * Time Reversal) -> This allows linear ME effect!
   - C2x * T (Rotation * Time Reversal)

Let's define this group.
-/
def mat_3_z : Matrix (Fin 3) (Fin 3) ℚ := ![![0, -1, 0], ![1, -1, 0], ![0, 0, 1]] -- Hexagonal basis C3
-- For simplicity, let's use orthogonal basis approximation for C3 if possible, or stick to matrices.
-- The provided mat_3_z above is for hexagonal coordinates.
-- Let's use a standard orthogonal matrix for C3z (requires sqrt(3), not in Rationals).
-- Rationals only support 90 degree rotations easily.
-- Let's switch to a Tetragonal Multiferroic example which fits our Rational number system.
-- Example: MnF2 is tetragonal rutile.
-- Or simulate a hypothetical "Tetragonal Cr2O3".

-- Hypothetical D4h-like Multiferroic
-- Symmetry:
-- 1. C4z (Spatial)
-- 2. I * T (Inversion * Time Reversal) -> Key for ME effect
-- 3. C2x * T
def gen_C4z : SPGElement := Op[mat_4_z, ^1]
def gen_IT  : SPGElement := Op[mat_inv, ^-1]
def gen_C2xT : SPGElement := Op[SPG.Material.MagneticGroup.mat_2_x, ^-1]

def ME_Group : List SPGElement := generate_group [gen_C4z, gen_IT, gen_C2xT]

end Demo.Multiferroic

def main : IO Unit := do
  IO.println "========================================"
  IO.println "Multiferroic Analysis: Hypothetical Tetragonal ME Material"
  IO.println "Symmetry: 4/m'm'm' (derived from generators C4z, I*T, C2x*T)"
  IO.println s!"Group Order: {Demo.Multiferroic.ME_Group.length}"
  IO.println "----------------------------------------"

  let group := Demo.Multiferroic.ME_Group

  -- 1. Check Primary Orders
  let fm := SPG.Model.Multiferroic.allows_ferromagnetism group
  let fe := SPG.Model.Multiferroic.allows_ferroelectricity group

  IO.println s!"Allowed Ferromagnetism: {fm}"
  IO.println s!"Allowed Ferroelectricity: {fe}"

  if fm.isEmpty && fe.isEmpty then
    IO.println "=> Order Parameters P and M are both forbidden in the ground state."
    IO.println "   (This is typical for linear magnetoelectrics like Cr2O3)"

  -- 2. Check Magnetoelectric Coupling
  IO.println "\nChecking Magnetoelectric Coupling (P = α M):"
  let me_terms := SPG.Model.Multiferroic.get_allowed_me_components group

  if me_terms.isEmpty then
    IO.println "  [FORBIDDEN] No linear magnetoelectric effect allowed."
  else
    IO.println s!"  [ALLOWED] Non-zero components: {me_terms}"

    if me_terms.contains "α_zz" then
      IO.println "  => Longitudinal ME effect allowed (Pz ~ Mz)"
    if me_terms.contains "α_xx" then
      IO.println "  => Transverse ME effect allowed (Px ~ Mx)"

  -- Compare with a standard Antiferromagnet (PT symmetric but no ME?)
  -- Re-use AFM from previous demo
  let afm_group := SPG.Material.MagneticGroup.Antiferromagnet_Group_PT
  IO.println "\n----------------------------------------"
  IO.println "Comparison: Standard PT-Symmetric AFM (D4h)"
  let me_afm := SPG.Model.Multiferroic.get_allowed_me_components afm_group
  IO.println s!"Allowed ME components: {me_afm}"
  -- Note: PT symmetry (I*T) actually ALLOWS ME effect usually.
  -- Let's see what the calculation says.
  -- In PT symmetric AFM:
  -- I*T: P -> P (I: -, T: even => -), M -> M (I: +, T: odd => -)
  -- Wait.
  -- P (Polar): I->-P, T->P. So I*T -> -P.
  -- M (Axial): I->M, T->-M. So I*T -> -M.
  -- P_i = alpha M_j
  -- -P = alpha (-M) => -P = - alpha M => P = alpha M.
  -- So I*T symmetry is COMPATIBLE with ME effect!
  -- Let's verify.
